"""add social tables

Revision ID: 0c80de3ebbbc
Revises: 352d595bf823
Create Date: 2026-06-20 23:17:01.230778

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c80de3ebbbc"
down_revision: Union[str, Sequence[str], None] = "352d595bf823"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("author_nick", sa.String(length=255), nullable=False),
        sa.Column("followers_count", sa.Integer(), nullable=True),
        sa.Column("year_yield", sa.Float(), nullable=True),
        sa.Column("month_yield", sa.Float(), nullable=True),
        sa.Column("strategy_description", sa.Text(), nullable=True),
        sa.Column("manual_reliability_score", sa.Float(), nullable=True),
        sa.Column("last_yield_update", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_fetched", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cache_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "author_nick", name="uq_author_profile_source_nick"),
    )
    op.create_table(
        "social_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("author_nick", sa.String(length=255), nullable=False),
        sa.Column("author_id", sa.String(length=255), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("tickers_mentioned", sa.JSON(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("processed", sa.Boolean(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_social_post_source_ext"),
    )
    op.create_index("ix_social_posts_author", "social_posts", ["source", "author_nick"], unique=False)
    op.create_index(op.f("ix_social_posts_author_nick"), "social_posts", ["author_nick"], unique=False)
    op.create_index("ix_social_posts_processed", "social_posts", ["processed"], unique=False)
    op.create_index(op.f("ix_social_posts_source"), "social_posts", ["source"], unique=False)
    op.create_table(
        "sentiment_signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("ticker", sa.String(length=20), nullable=True),
        sa.Column("bullish_score", sa.Float(), nullable=True),
        sa.Column("bearish_score", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("composite_score", sa.Float(), nullable=True),
        sa.Column("llm_reasoning", sa.Text(), nullable=True),
        sa.Column("source_weight", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["social_posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sentiment_signals_ticker"), "sentiment_signals", ["ticker"], unique=False)
    op.create_index("ix_sentiment_signals_ticker_date", "sentiment_signals", ["ticker", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sentiment_signals_ticker_date", table_name="sentiment_signals")
    op.drop_index(op.f("ix_sentiment_signals_ticker"), table_name="sentiment_signals")
    op.drop_table("sentiment_signals")
    op.drop_index(op.f("ix_social_posts_source"), table_name="social_posts")
    op.drop_index("ix_social_posts_processed", table_name="social_posts")
    op.drop_index(op.f("ix_social_posts_author_nick"), table_name="social_posts")
    op.drop_index("ix_social_posts_author", table_name="social_posts")
    op.drop_table("social_posts")
    op.drop_table("author_profiles")
    # ### end Alembic commands ###
