"""add feature_cache table

Revision ID: 40358fbb008e
Revises: b52c52467be4
Create Date: 2026-06-15 10:16:33.333023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40358fbb008e'
down_revision: Union[str, Sequence[str], None] = 'b52c52467be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('feature_type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'feature_type', 'date', name='uq_feature_cache')
    )
    op.create_index('ix_feature_ticker_type', 'feature_cache', ['ticker', 'feature_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feature_ticker_type', table_name='feature_cache')
    op.drop_table('feature_cache')
    # ### end Alembic commands ###
