"""add all missing tables

Revision ID: 55e690c47941
Revises: b26d8d834001
Create Date: 2026-06-17 16:53:31.119138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e690c47941'
down_revision: Union[str, Sequence[str], None] = 'b26d8d834001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('order_id_ext', sa.String(length=100), nullable=True),
    sa.Column('figi', sa.String(length=50), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('executed_price', sa.Float(), nullable=True),
    sa.Column('executed_quantity', sa.Integer(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_created', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_ticker'), 'orders', ['ticker'], unique=False)
    op.create_table('trade_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_log_ct', 'trade_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_log_ticker'), 'trade_log', ['ticker'], unique=False)
    op.create_index('ix_trade_log_tkr', 'trade_log', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_log_tkr', table_name='trade_log')
    op.drop_index(op.f('ix_trade_log_ticker'), table_name='trade_log')
    op.drop_index('ix_trade_log_ct', table_name='trade_log')
    op.drop_table('trade_log')
    op.drop_index(op.f('ix_orders_ticker'), table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_created', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
