"""add metric_snapshots and daily_reports

Revision ID: 87ed6b3d580d
Revises: 0c80de3ebbbc
Create Date: 2026-06-21 23:34:31.231789

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87ed6b3d580d"
down_revision: Union[str, Sequence[str], None] = "0c80de3ebbbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_buy", sa.Integer(), nullable=True),
        sa.Column("total_sell", sa.Integer(), nullable=True),
        sa.Column("total_hold", sa.Integer(), nullable=True),
        sa.Column("market_score_avg", sa.Float(), nullable=True),
        sa.Column("market_score_trend", sa.String(length=10), nullable=True),
        sa.Column("portfolio_signals", sa.JSON(), nullable=True),
        sa.Column("report_text", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_daily_reports_date"), "daily_reports", ["date"], unique=True)
    op.create_table(
        "metric_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period", sa.String(length=10), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("rsi", sa.Float(), nullable=True),
        sa.Column("macd_line", sa.Float(), nullable=True),
        sa.Column("macd_signal", sa.Float(), nullable=True),
        sa.Column("macd_hist", sa.Float(), nullable=True),
        sa.Column("sma_20", sa.Float(), nullable=True),
        sa.Column("sma_50", sa.Float(), nullable=True),
        sa.Column("sma_200", sa.Float(), nullable=True),
        sa.Column("signal_action", sa.String(length=20), nullable=True),
        sa.Column("signal_score", sa.Float(), nullable=True),
        sa.Column("signal_confidence", sa.Float(), nullable=True),
        sa.Column("delta_price_pct", sa.Float(), nullable=True),
        sa.Column("delta_score", sa.Float(), nullable=True),
        sa.Column("delta_rsi", sa.Float(), nullable=True),
        sa.Column("delta_action_changed", sa.Boolean(), nullable=True),
        sa.Column("market_score_avg", sa.Float(), nullable=True),
        sa.Column("social_score_avg", sa.Float(), nullable=True),
        sa.Column("geo_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_metric_snapshots_period"), "metric_snapshots", ["period"], unique=False)
    op.create_index("ix_snapshot_instr_period", "metric_snapshots", ["instrument_id", "period"], unique=False)
    op.create_index("ix_snapshot_taken", "metric_snapshots", ["taken_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_snapshot_taken", table_name="metric_snapshots")
    op.drop_index("ix_snapshot_instr_period", table_name="metric_snapshots")
    op.drop_index(op.f("ix_metric_snapshots_period"), table_name="metric_snapshots")
    op.drop_table("metric_snapshots")
    op.drop_index(op.f("ix_daily_reports_date"), table_name="daily_reports")
    op.drop_table("daily_reports")
    # ### end Alembic commands ###
