"""add_paper_trading_tables

Revision ID: b2e409397a74
Revises: fffa98744b80
Create Date: 2026-07-04 21:33:58.318456

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b2e409397a74'
down_revision: Union[str, Sequence[str], None] = 'fffa98744b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('executed_price', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_orders_created', 'paper_orders', ['created_at'], unique=False)
    op.create_index('ix_paper_orders_ticker', 'paper_orders', ['ticker'], unique=False)
    op.create_index('ix_paper_orders_user', 'paper_orders', ['user_id'], unique=False)
    op.create_table('paper_trade_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('balance_before', sa.Float(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['paper_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_trade_log_ticker', 'paper_trade_log', ['ticker'], unique=False)
    op.create_index('ix_paper_trade_log_user', 'paper_trade_log', ['user_id'], unique=False)
    op.alter_column('company_risk_history', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('feature_cache', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('feature_cache', sa.Column('ttl_hours', sa.Integer(), nullable=True))
    op.alter_column('geopolitical_risk_history', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_geopolitical_risk_date'), table_name='geopolitical_risk_history')
    op.add_column('instruments', sa.Column('exchange', sa.String(length=10), server_default=sa.text("'MOEX'"), nullable=True))
    op.drop_index(op.f('ix_news_created_at'), table_name='news')
    op.create_foreign_key(None, 'news', 'news_events', ['event_id'], ['id'])
    op.alter_column('news_company_impacts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_news_company_impacts_instrument'), table_name='news_company_impacts')
    op.drop_index(op.f('ix_news_company_impacts_news'), table_name='news_company_impacts')
    op.create_index(op.f('ix_news_company_impacts_instrument_id'), 'news_company_impacts', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_news_company_impacts_news_id'), 'news_company_impacts', ['news_id'], unique=False)
    op.alter_column('news_events', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('news_events', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_news_events_created_at'), table_name='news_events')
    op.create_index(op.f('ix_news_events_subcategory'), 'news_events', ['subcategory'], unique=False)
    op.alter_column('news_sector_impacts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_news_sector_impacts_news'), table_name='news_sector_impacts')
    op.drop_index(op.f('ix_news_sector_impacts_type'), table_name='news_sector_impacts')
    op.create_index(op.f('ix_news_sector_impacts_impact_type'), 'news_sector_impacts', ['impact_type'], unique=False)
    op.create_index(op.f('ix_news_sector_impacts_news_id'), 'news_sector_impacts', ['news_id'], unique=False)
    op.alter_column('sector_risk_history', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_sector_risk_sector_date'), table_name='sector_risk_history')
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_sector_risk_sector_date'), 'sector_risk_history', ['sector', 'date'], unique=False)
    op.alter_column('sector_risk_history', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_news_sector_impacts_news_id'), table_name='news_sector_impacts')
    op.drop_index(op.f('ix_news_sector_impacts_impact_type'), table_name='news_sector_impacts')
    op.create_index(op.f('ix_news_sector_impacts_type'), 'news_sector_impacts', ['impact_type'], unique=False)
    op.create_index(op.f('ix_news_sector_impacts_news'), 'news_sector_impacts', ['news_id'], unique=False)
    op.alter_column('news_sector_impacts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_news_events_subcategory'), table_name='news_events')
    op.create_index(op.f('ix_news_events_created_at'), 'news_events', ['created_at'], unique=False)
    op.alter_column('news_events', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('news_events', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_news_company_impacts_news_id'), table_name='news_company_impacts')
    op.drop_index(op.f('ix_news_company_impacts_instrument_id'), table_name='news_company_impacts')
    op.create_index(op.f('ix_news_company_impacts_news'), 'news_company_impacts', ['news_id'], unique=False)
    op.create_index(op.f('ix_news_company_impacts_instrument'), 'news_company_impacts', ['instrument_id'], unique=False)
    op.alter_column('news_company_impacts', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_index(op.f('ix_news_created_at'), 'news', ['created_at'], unique=False)
    op.drop_column('instruments', 'exchange')
    op.create_index(op.f('ix_geopolitical_risk_date'), 'geopolitical_risk_history', ['date'], unique=False)
    op.alter_column('geopolitical_risk_history', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('feature_cache', 'ttl_hours')
    op.drop_column('feature_cache', 'version')
    op.alter_column('company_risk_history', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index('ix_paper_trade_log_user', table_name='paper_trade_log')
    op.drop_index('ix_paper_trade_log_ticker', table_name='paper_trade_log')
    op.drop_table('paper_trade_log')
    op.drop_index('ix_paper_orders_user', table_name='paper_orders')
    op.drop_index('ix_paper_orders_ticker', table_name='paper_orders')
    op.drop_index('ix_paper_orders_created', table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_table('paper_accounts')
    # ### end Alembic commands ###
