from __future__ import annotations

_INTENT_MAP: dict[str, list[str]] = {
    "portfolio_value": [
        "portfolio",
        "портфель",
        "value",
        "стоимость",
        "worth",
        "how much",
        "balance",
        "баланс",
        "holdings",
        "позиции",
        "positions",
    ],
    "scenario_analysis": [
        "scenario",
        "сценарий",
        "what if",
        "что если",
        "crash",
        "обвал",
        "stress",
        "стресс",
        "macro",
        "макро",
        "shock",
        "шок",
    ],
    "news_impact": [
        "news",
        "новости",
        "новость",
        "impact",
        "влияние",
        "effect",
        "sentiment",
        "сентимент",
        "affect",
        "повлия",
        "последн",
    ],
    "top_picks": [
        "top",
        "топ",
        "best",
        "лучш",
        "pick",
        "выбор",
        "recommend",
        "рекомендац",
        "signal",
        "сигнал",
        "buy",
        "купить",
    ],
    "risk_metrics": [
        "risk",
        "риск",
        "var",
        "cvar",
        "value at risk",
        "drawdown",
        "просадк",
        "volatility",
        "волатильност",
        "опасн",
    ],
    "rebalance": [
        "rebalance",
        "ребаланс",
        "rebalancing",
        "drift",
        "отклонен",
        "target",
        "целев",
        "overweight",
        "перевес",
    ],
    "instrument_info": [
        "instrument",
        "инструмент",
        "ticker",
        "тикер",
        "price",
        "цена",
        "pe",
        "p/e",
        "market cap",
        "капитализация",
        "sector",
        "сектор",
        "about",
        "о компании",
        "что такое",
        "кто такой",
        "описание",
        "info",
        "информация",
        "характеристик",
    ],
    "macro_query": [
        "macro",
        "макро",
        "cbr",
        "цб",
        "ключевая ставка",
        "inflation",
        "инфляция",
        "gdp",
        "ввп",
        "экономика",
        "economy",
        "ставка",
        "ставку",
        "процент",
    ],
    "compare": [
        "compare",
        "сравн",
        "vs",
        "против",
        "better",
        "лучш",
        "difference",
        "разниц",
        "which",
        "какой",
        "или",
    ],
}

_KNOWN_SECTORS: list[str] = [
    "финансы",
    "нефть",
    "it",
    "металлы",
    "электроэнергетика",
    "потреб",
    "химия",
    "транспорт",
    "телеком",
    "строительство",
    "машиностроение",
    "авиация",
    "ритейл",
    "здравоохран",
    "инфраструктур",
    "сельское хозяйство",
    "добыча",
    "обрабатывающ",
    "инновации",
]

_ABBREVIATIONS: dict[str, str] = {
    "сбер": "сбер банк",
    "газпром": "газпром",
    "сбп": "сбер банк",
    "втб": "втб банк",
    "лукойл": "лукойл",
    "роснефть": "роснефть",
    "яндекс": "яндекс",
    "новост": "новости",
}

_ENGLISH_TO_RUSSIAN: dict[str, str] = {
    "portfolio": "портфель",
    "value": "стоимость",
    "news": "новости",
    "risk": "риск",
    "buy": "купить",
    "sell": "продать",
    "top": "топ",
    "best": "лучший",
    "scenario": "сценарий",
    "crash": "обвал",
    "compare": "сравнить",
    "vs": "против",
    "macro": "макро",
    "rate": "ставка",
    "inflation": "инфляция",
    "gdp": "ввп",
    "economy": "экономика",
}

_TIMEFRAME_WORDS: dict[str, str] = {
    "день": "1d",
    "дня": "1d",
    "дней": "1d",
    "daily": "1d",
    "недел": "1w",
    "weekly": "1w",
    "месяц": "1m",
    "месяца": "1m",
    "месяцев": "1m",
    "month": "1m",
    "год": "1y",
    "года": "1y",
    "лет": "1y",
    "year": "1y",
    "annual": "1y",
    "quarter": "1q",
    "квартал": "1q",
}
