import { 
  Search, Star, Wallet, ChartBar, TrendingUp, TrendingDown, 
  Building2, Bell, Settings, LogOut, User, Plus, Minus,
  ArrowUp, ArrowDown, ArrowRight, Download, Upload,
  Calendar, Clock, Percent, DollarSign, Shield,
  Eye, EyeOff, MoreHorizontal, Scale, BarChart3,
  PiggyBank, Landmark, Receipt, Sparkles, Ban, RotateCcw,
  ChevronDown, ChevronUp, ChevronsUpDown, ChevronLeft, ChevronRight,
  X, Check, AlertTriangle, Info, HelpCircle,
  Hash, Ticket, Banknote, Monitor, Columns3,
} from "lucide-react";

export const Icons = {
  search: Search,
  star: Star,
  wallet: Wallet,
  chart: ChartBar,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  building: Building2,
  bell: Bell,
  settings: Settings,
  logout: LogOut,
  user: User,
  plus: Plus,
  minus: Minus,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowRight: ArrowRight,
  download: Download,
  upload: Upload,
  calendar: Calendar,
  clock: Clock,
  percent: Percent,
  dollar: DollarSign,
  shield: Shield,
  eye: Eye,
  eyeOff: EyeOff,
  more: MoreHorizontal,
  scale: Scale,
  chartBar: BarChart3,
  piggyBank: PiggyBank,
  landMark: Landmark,
  receipt: Receipt,
  sparkles: Sparkles,
  ban: Ban,
  rotate: RotateCcw,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronsUpDown: ChevronsUpDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  x: X,
  check: Check,
  alert: AlertTriangle,
  info: Info,
  help: HelpCircle,
  hash: Hash,
  ticket: Ticket,
  banknote: Banknote,
  monitor: Monitor,
  columns: Columns3,
} as const;
