# ruff: noqa: E501
"""Real historical market events for Russian market."""

from datetime import date
from typing import Any

REAL_EVENTS: list[dict[str, Any]] = [
    {
        "date": date(2008, 9, 15),
        "event_type": "global_crisis",
        "title": "Банкротство Lehman Brothers",
        "severity": 0.95,
        "market_impact_pct": -17.0,
        "source": "historical",
    },
    {
        "date": date(2008, 10, 6),
        "event_type": "global_crisis",
        "title": "Обвал мировых фондовых рынков",
        "severity": 0.9,
        "market_impact_pct": -15.0,
        "source": "historical",
    },
    {
        "date": date(2008, 11, 20),
        "event_type": "global_crisis",
        "title": "Дно кризиса: IMOEX на минимуме",
        "severity": 0.85,
        "market_impact_pct": -5.0,
        "source": "historical",
    },
    {
        "date": date(2008, 12, 1),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 13% для защиты рубля",
        "severity": 0.7,
        "market_impact_pct": -3.5,
        "source": "historical",
    },
    {
        "date": date(2009, 1, 15),
        "event_type": "oil_shock",
        "title": "Нефть Brent упала до $36 — минимум кризиса",
        "severity": 0.8,
        "market_impact_pct": -4.2,
        "source": "historical",
    },
    {
        "date": date(2009, 3, 10),
        "event_type": "global_crisis",
        "title": "Начало восстановления рынков после кризиса",
        "severity": 0.4,
        "market_impact_pct": 5.0,
        "source": "historical",
    },
    {
        "date": date(2009, 4, 24),
        "event_type": "rate_decision",
        "title": "ЦБ начал снижать ставку — сигнал к восстановлению",
        "severity": 0.5,
        "market_impact_pct": 3.0,
        "source": "historical",
    },
    {
        "date": date(2010, 5, 6),
        "event_type": "global_crisis",
        "title": "Flash Crash в США — падение Dow на 9%",
        "severity": 0.6,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2010, 6, 1),
        "event_type": "macro_data",
        "title": "Засуха в России — рост цен на зерно",
        "severity": 0.3,
        "market_impact_pct": -1.5,
        "source": "historical",
    },
    {
        "date": date(2011, 3, 11),
        "event_type": "natural_disaster",
        "title": "Землетрясение и цунами в Японии — падение мировых рынков",
        "severity": 0.65,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2011, 8, 5),
        "event_type": "global_crisis",
        "title": "S&P понизило рейтинг США — долговой кризис",
        "severity": 0.7,
        "market_impact_pct": -5.0,
        "source": "historical",
    },
    {
        "date": date(2011, 9, 21),
        "event_type": "rate_decision",
        "title": "ФРС запускает Operation Twist",
        "severity": 0.4,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2012, 1, 1),
        "event_type": "political",
        "title": "Вступление России в ВТО",
        "severity": 0.35,
        "market_impact_pct": 1.0,
        "source": "historical",
    },
    {
        "date": date(2012, 3, 4),
        "event_type": "political",
        "title": "Президентские выборы в России — победа Путина",
        "severity": 0.4,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2012, 5, 6),
        "event_type": "political",
        "title": "Протесты в Москве — рост политической неопределённости",
        "severity": 0.45,
        "market_impact_pct": -2.5,
        "source": "historical",
    },
    {
        "date": date(2012, 9, 13),
        "event_type": "rate_decision",
        "title": "ФРС запускает QE3",
        "severity": 0.55,
        "market_impact_pct": 3.5,
        "source": "historical",
    },
    {
        "date": date(2013, 1, 1),
        "event_type": "macro_data",
        "title": "Рост ВВП РФ замедлился до 1.3%",
        "severity": 0.3,
        "market_impact_pct": -1.0,
        "source": "historical",
    },
    {
        "date": date(2013, 6, 20),
        "event_type": "rate_decision",
        "title": "ФРС сигнализирует о сворачивании QE — Taper Tantrum",
        "severity": 0.65,
        "market_impact_pct": -4.5,
        "source": "historical",
    },
    {
        "date": date(2014, 2, 22),
        "event_type": "geopolitical",
        "title": "Смена власти на Украине — начало кризиса",
        "severity": 0.7,
        "market_impact_pct": -5.0,
        "source": "historical",
    },
    {
        "date": date(2014, 3, 3),
        "event_type": "geopolitical",
        "title": "Военные действия в Крыму — падение MOEX",
        "severity": 0.8,
        "market_impact_pct": -10.0,
        "source": "historical",
    },
    {
        "date": date(2014, 3, 18),
        "event_type": "geopolitical",
        "title": "Присоединение Крыма к РФ — первые санкции США/ЕС",
        "severity": 0.85,
        "market_impact_pct": -8.0,
        "source": "historical",
    },
    {
        "date": date(2014, 4, 28),
        "event_type": "sanctions",
        "title": "Секторальные санкции США против РФ",
        "severity": 0.8,
        "market_impact_pct": -6.0,
        "source": "historical",
    },
    {
        "date": date(2014, 7, 16),
        "event_type": "sanctions",
        "title": "Новые санкции США — запрет на поставки технологий",
        "severity": 0.75,
        "market_impact_pct": -5.0,
        "source": "historical",
    },
    {
        "date": date(2014, 7, 29),
        "event_type": "sanctions",
        "title": "Санкции ЕС против российского нефтегаза и оборонки",
        "severity": 0.8,
        "market_impact_pct": -7.0,
        "source": "historical",
    },
    {
        "date": date(2014, 9, 12),
        "event_type": "sanctions",
        "title": "Ужесточение санкций — ограничения на госдолг РФ",
        "severity": 0.7,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2014, 10, 16),
        "event_type": "oil_shock",
        "title": "Нефть Brent обвалилась до $85",
        "severity": 0.75,
        "market_impact_pct": -5.0,
        "source": "historical",
    },
    {
        "date": date(2014, 12, 1),
        "event_type": "oil_shock",
        "title": "Нефть Brent упала до $70",
        "severity": 0.8,
        "market_impact_pct": -6.0,
        "source": "historical",
    },
    {
        "date": date(2014, 12, 11),
        "event_type": "oil_shock",
        "title": "Нефть Brent ниже $65 — паника на рынке",
        "severity": 0.85,
        "market_impact_pct": -7.0,
        "source": "historical",
    },
    {
        "date": date(2014, 12, 16),
        "event_type": "financial_crisis",
        "title": "Чёрный вторник: рубль обвалился до 80/USD",
        "severity": 0.95,
        "market_impact_pct": -12.0,
        "source": "historical",
    },
    {
        "date": date(2014, 12, 16),
        "event_type": "rate_decision",
        "title": "ЦБ экстренно поднял ставку до 17%",
        "severity": 0.95,
        "market_impact_pct": 5.0,
        "source": "historical",
    },
    {
        "date": date(2015, 1, 15),
        "event_type": "rate_decision",
        "title": "Швейцарский Нацбанк отпустил франк — паника на forex",
        "severity": 0.5,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2015, 1, 30),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 15%",
        "severity": 0.4,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2015, 2, 12),
        "event_type": "geopolitical",
        "title": "Минские соглашения по Донбассу",
        "severity": 0.5,
        "market_impact_pct": 3.0,
        "source": "historical",
    },
    {
        "date": date(2015, 3, 13),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 14%",
        "severity": 0.4,
        "market_impact_pct": 1.5,
        "source": "historical",
    },
    {
        "date": date(2015, 4, 30),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 12.5%",
        "severity": 0.45,
        "market_impact_pct": 3.0,
        "source": "historical",
    },
    {
        "date": date(2015, 5, 5),
        "event_type": "macro_data",
        "title": "ВВП РФ упал на 1.9% в Q1",
        "severity": 0.4,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2015, 6, 15),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 11.5%",
        "severity": 0.4,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2015, 7, 31),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 11%",
        "severity": 0.35,
        "market_impact_pct": 1.5,
        "source": "historical",
    },
    {
        "date": date(2015, 8, 11),
        "event_type": "global_crisis",
        "title": "Девальвация юаня — падение мировых рынков",
        "severity": 0.6,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2015, 8, 24),
        "event_type": "global_crisis",
        "title": "Чёрный понедельник в Китае — Shanghai -8.5%",
        "severity": 0.65,
        "market_impact_pct": -5.0,
        "source": "historical",
    },
    {
        "date": date(2015, 9, 11),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 11%",
        "severity": 0.2,
        "market_impact_pct": 0.5,
        "source": "historical",
    },
    {
        "date": date(2015, 11, 16),
        "event_type": "terror",
        "title": "Теракты в Париже — падение рынков",
        "severity": 0.55,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2015, 12, 4),
        "event_type": "rate_decision",
        "title": "ФРС повысила ставку впервые за 9 лет",
        "severity": 0.5,
        "market_impact_pct": -1.5,
        "source": "historical",
    },
    {
        "date": date(2015, 12, 11),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 11%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2016, 1, 11),
        "event_type": "oil_shock",
        "title": "Нефть Brent упала до $30",
        "severity": 0.85,
        "market_impact_pct": -6.0,
        "source": "historical",
    },
    {
        "date": date(2016, 1, 21),
        "event_type": "oil_shock",
        "title": "Нефть Brent на минимуме $27.88",
        "severity": 0.9,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2016, 1, 29),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 11%",
        "severity": 0.2,
        "market_impact_pct": 0.5,
        "source": "historical",
    },
    {
        "date": date(2016, 2, 11),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 11% — сигнал к снижению",
        "severity": 0.25,
        "market_impact_pct": 1.0,
        "source": "historical",
    },
    {
        "date": date(2016, 3, 18),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 11%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2016, 4, 15),
        "event_type": "oil_shock",
        "title": "Срыв сделки ОПЕК+ в Дохе — обвал нефти",
        "severity": 0.6,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2016, 4, 29),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 11%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2016, 6, 10),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 10.5%",
        "severity": 0.5,
        "market_impact_pct": 2.5,
        "source": "historical",
    },
    {
        "date": date(2016, 6, 23),
        "event_type": "political",
        "title": "Brexit — Великобритания выходит из ЕС",
        "severity": 0.75,
        "market_impact_pct": -6.0,
        "source": "historical",
    },
    {
        "date": date(2016, 7, 29),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 10%",
        "severity": 0.45,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2016, 9, 16),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 10%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2016, 10, 28),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 10%",
        "severity": 0.2,
        "market_impact_pct": -0.5,
        "source": "historical",
    },
    {
        "date": date(2016, 11, 9),
        "event_type": "political",
        "title": "Победа Трампа на выборах в США — ралли на рынках",
        "severity": 0.6,
        "market_impact_pct": 3.0,
        "source": "historical",
    },
    {
        "date": date(2016, 11, 30),
        "event_type": "oil_shock",
        "title": "ОПЕК+ договорился о сокращении добычи — нефть растёт",
        "severity": 0.65,
        "market_impact_pct": 4.0,
        "source": "historical",
    },
    {
        "date": date(2016, 12, 14),
        "event_type": "rate_decision",
        "title": "ФРС повысила ставку — прогноз 3 повышения на 2017",
        "severity": 0.4,
        "market_impact_pct": -1.0,
        "source": "historical",
    },
    {
        "date": date(2017, 1, 1),
        "event_type": "macro_data",
        "title": "Рост ВВП РФ возобновился после рецессии",
        "severity": 0.3,
        "market_impact_pct": 1.0,
        "source": "historical",
    },
    {
        "date": date(2017, 3, 24),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 9.75%",
        "severity": 0.4,
        "market_impact_pct": 1.5,
        "source": "historical",
    },
    {
        "date": date(2017, 4, 28),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 9.25%",
        "severity": 0.4,
        "market_impact_pct": 1.5,
        "source": "historical",
    },
    {
        "date": date(2017, 6, 16),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 9%",
        "severity": 0.35,
        "market_impact_pct": 1.5,
        "source": "historical",
    },
    {
        "date": date(2017, 7, 28),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 9% и сигнал к дальнейшему снижению",
        "severity": 0.4,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2017, 9, 15),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 8.5%",
        "severity": 0.45,
        "market_impact_pct": 2.5,
        "source": "historical",
    },
    {
        "date": date(2017, 10, 27),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 8.25%",
        "severity": 0.4,
        "market_impact_pct": 1.0,
        "source": "historical",
    },
    {
        "date": date(2017, 12, 15),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 7.75%",
        "severity": 0.45,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2018, 2, 5),
        "event_type": "global_crisis",
        "title": "Volmageddon — обвал VIX, падение S&P на -4%",
        "severity": 0.5,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2018, 3, 23),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 7.25%",
        "severity": 0.4,
        "market_impact_pct": 1.5,
        "source": "historical",
    },
    {
        "date": date(2018, 4, 6),
        "event_type": "sanctions",
        "title": "Санкции США против компаний Дерипаски (РУСАЛа)",
        "severity": 0.85,
        "market_impact_pct": -10.0,
        "source": "historical",
    },
    {
        "date": date(2018, 4, 9),
        "event_type": "sanctions",
        "title": "Обвал рынка РФ из-за санкций — РУСАЛ -50%",
        "severity": 0.9,
        "market_impact_pct": -12.0,
        "source": "historical",
    },
    {
        "date": date(2018, 4, 11),
        "event_type": "geopolitical",
        "title": "Угрозы Трампа по Сирии — рост геополитики",
        "severity": 0.55,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2018, 5, 29),
        "event_type": "political",
        "title": "Италия: политический кризис — падение рынков ЕС",
        "severity": 0.4,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2018, 6, 1),
        "event_type": "geopolitical",
        "title": "Саммит Путин-Трамп в Хельсинки",
        "severity": 0.35,
        "market_impact_pct": 1.5,
        "source": "historical",
    },
    {
        "date": date(2018, 8, 8),
        "event_type": "sanctions",
        "title": "Новые санкции США из-за дела Скрипалей",
        "severity": 0.65,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2018, 9, 14),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 7.25%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2018, 10, 1),
        "event_type": "oil_shock",
        "title": "Нефть Brent выше $85 — максимум с 2014",
        "severity": 0.5,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2018, 10, 11),
        "event_type": "global_crisis",
        "title": "Технологический обвал в США — NASDAQ -4%",
        "severity": 0.5,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2018, 11, 5),
        "event_type": "oil_shock",
        "title": "Нефть Brent упала с $85 до $73 за месяц",
        "severity": 0.6,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2018, 12, 14),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 7.75%",
        "severity": 0.55,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2018, 12, 24),
        "event_type": "global_crisis",
        "title": "Рождественский обвал: S&P -20% от максимумов",
        "severity": 0.6,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2019, 1, 1),
        "event_type": "macro_data",
        "title": "Повышение НДС до 20% в РФ",
        "severity": 0.35,
        "market_impact_pct": -1.5,
        "source": "historical",
    },
    {
        "date": date(2019, 2, 8),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 7.75%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2019, 3, 22),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 7.75%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2019, 4, 26),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 7.75%",
        "severity": 0.2,
        "market_impact_pct": 0.5,
        "source": "historical",
    },
    {
        "date": date(2019, 5, 5),
        "event_type": "trade_war",
        "title": "Трамп повысил пошлины на китайские товары — торговая война",
        "severity": 0.65,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2019, 6, 14),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 7.5%",
        "severity": 0.4,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2019, 7, 26),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 7.25%",
        "severity": 0.4,
        "market_impact_pct": 1.5,
        "source": "historical",
    },
    {
        "date": date(2019, 9, 6),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 7%",
        "severity": 0.45,
        "market_impact_pct": 2.5,
        "source": "historical",
    },
    {
        "date": date(2019, 10, 25),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 6.5%",
        "severity": 0.5,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2019, 12, 13),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 6.25%",
        "severity": 0.45,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2020, 1, 30),
        "event_type": "pandemic",
        "title": "ВОЗ объявила чрезвычайную ситуацию из-за COVID-19",
        "severity": 0.6,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2020, 2, 7),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 6.25%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2020, 2, 28),
        "event_type": "pandemic",
        "title": "Первый случай COVID в РФ — обвал рынков",
        "severity": 0.7,
        "market_impact_pct": -8.0,
        "source": "historical",
    },
    {
        "date": date(2020, 3, 6),
        "event_type": "oil_shock",
        "title": "Развал сделки ОПЕК+ — нефть рухнула на 30%",
        "severity": 0.95,
        "market_impact_pct": -15.0,
        "source": "historical",
    },
    {
        "date": date(2020, 3, 9),
        "event_type": "oil_shock",
        "title": "Чёрный понедельник: нефть -30%, MOEX -12%",
        "severity": 0.95,
        "market_impact_pct": -12.0,
        "source": "historical",
    },
    {
        "date": date(2020, 3, 12),
        "event_type": "pandemic",
        "title": "Трамп закрыл границы с Европой — паника на рынках",
        "severity": 0.8,
        "market_impact_pct": -8.0,
        "source": "historical",
    },
    {
        "date": date(2020, 3, 18),
        "event_type": "pandemic",
        "title": "MOEX на дне кризиса — индекс ниже 2100",
        "severity": 0.9,
        "market_impact_pct": -5.0,
        "source": "historical",
    },
    {
        "date": date(2020, 3, 23),
        "event_type": "rate_decision",
        "title": "ФРС запускает неограниченный QE",
        "severity": 0.8,
        "market_impact_pct": 7.0,
        "source": "historical",
    },
    {
        "date": date(2020, 4, 1),
        "event_type": "oil_shock",
        "title": "Нефть Brent упала до $18",
        "severity": 0.9,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2020, 4, 9),
        "event_type": "oil_shock",
        "title": "ОПЕК+ договорился о рекордном сокращении добычи",
        "severity": 0.65,
        "market_impact_pct": 5.0,
        "source": "historical",
    },
    {
        "date": date(2020, 4, 20),
        "event_type": "oil_shock",
        "title": "Нефть WTI ушла в минус (-$37) — историческое событие",
        "severity": 0.95,
        "market_impact_pct": -5.0,
        "source": "historical",
    },
    {
        "date": date(2020, 4, 24),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 5.5%",
        "severity": 0.5,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2020, 5, 1),
        "event_type": "oil_shock",
        "title": "Нефть Brent восстановилась до $30",
        "severity": 0.35,
        "market_impact_pct": 3.0,
        "source": "historical",
    },
    {
        "date": date(2020, 5, 25),
        "event_type": "geopolitical",
        "title": "Убийство Джорджа Флойда — протесты в США",
        "severity": 0.35,
        "market_impact_pct": -1.0,
        "source": "historical",
    },
    {
        "date": date(2020, 6, 19),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 4.5%",
        "severity": 0.55,
        "market_impact_pct": 2.5,
        "source": "historical",
    },
    {
        "date": date(2020, 7, 24),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 4.25%",
        "severity": 0.45,
        "market_impact_pct": 1.5,
        "source": "historical",
    },
    {
        "date": date(2020, 8, 3),
        "event_type": "pandemic",
        "title": "Россия зарегистрировала вакцину Спутник V",
        "severity": 0.35,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2020, 9, 18),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 4.25%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2020, 10, 5),
        "event_type": "political",
        "title": "Трамп госпитализирован с COVID — рост волатильности",
        "severity": 0.45,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2020, 10, 30),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 4.25%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2020, 11, 9),
        "event_type": "pandemic",
        "title": "Pfizer объявила об эффективности вакцины 90% — ралли",
        "severity": 0.6,
        "market_impact_pct": 4.0,
        "source": "historical",
    },
    {
        "date": date(2020, 12, 18),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 4.25%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2021, 1, 1),
        "event_type": "macro_data",
        "title": "Рост ВВП РФ после COVID — восстановление",
        "severity": 0.3,
        "market_impact_pct": 1.5,
        "source": "historical",
    },
    {
        "date": date(2021, 2, 12),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 4.25%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2021, 3, 19),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 4.5% — начало цикла",
        "severity": 0.6,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2021, 4, 2),
        "event_type": "sanctions",
        "title": "Санкции США за вмешательство в выборы",
        "severity": 0.45,
        "market_impact_pct": -2.5,
        "source": "historical",
    },
    {
        "date": date(2021, 4, 15),
        "event_type": "sanctions",
        "title": "Санкции на госдолг РФ — запрет покупки ОФЗ",
        "severity": 0.7,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2021, 4, 23),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 5%",
        "severity": 0.55,
        "market_impact_pct": -1.5,
        "source": "historical",
    },
    {
        "date": date(2021, 5, 1),
        "event_type": "political",
        "title": "Протесты в Беларуси — посадка Ryanair",
        "severity": 0.3,
        "market_impact_pct": -1.0,
        "source": "historical",
    },
    {
        "date": date(2021, 6, 11),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 5.5%",
        "severity": 0.55,
        "market_impact_pct": -1.5,
        "source": "historical",
    },
    {
        "date": date(2021, 7, 23),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 6.5%",
        "severity": 0.6,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2021, 9, 10),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 6.75%",
        "severity": 0.55,
        "market_impact_pct": -1.5,
        "source": "historical",
    },
    {
        "date": date(2021, 10, 6),
        "event_type": "macro_data",
        "title": "Инфляция в РФ разогналась до 7.4%",
        "severity": 0.5,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2021, 10, 22),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 7.5%",
        "severity": 0.6,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2021, 11, 26),
        "event_type": "pandemic",
        "title": "Новый штамм Omicron — паника на рынках",
        "severity": 0.55,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2021, 12, 17),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 8.5% — седьмое повышение",
        "severity": 0.65,
        "market_impact_pct": -2.5,
        "source": "historical",
    },
    {
        "date": date(2022, 1, 1),
        "event_type": "political",
        "title": "Протесты в Казахстане — ввод войск ОДКБ",
        "severity": 0.4,
        "market_impact_pct": -1.5,
        "source": "historical",
    },
    {
        "date": date(2022, 2, 14),
        "event_type": "geopolitical",
        "title": "Эскалация на границе РФ-Украина — рост геополитики",
        "severity": 0.7,
        "market_impact_pct": -5.0,
        "source": "historical",
    },
    {
        "date": date(2022, 2, 22),
        "event_type": "geopolitical",
        "title": "Признание ДНР/ЛНР — падение MOEX на 10%",
        "severity": 0.85,
        "market_impact_pct": -10.0,
        "source": "historical",
    },
    {
        "date": date(2022, 2, 24),
        "event_type": "geopolitical",
        "title": "Начало СВО на Украине — исторический обвал",
        "severity": 1.0,
        "market_impact_pct": -33.0,
        "source": "historical",
    },
    {
        "date": date(2022, 2, 28),
        "event_type": "sanctions",
        "title": "Жёсткие санкции Запада — заморозка резервов ЦБ РФ",
        "severity": 1.0,
        "market_impact_pct": -20.0,
        "source": "historical",
    },
    {
        "date": date(2022, 2, 28),
        "event_type": "rate_decision",
        "title": "ЦБ экстренно поднял ставку до 20%",
        "severity": 1.0,
        "market_impact_pct": 5.0,
        "source": "historical",
    },
    {
        "date": date(2022, 3, 1),
        "event_type": "sanctions",
        "title": "Отключение РФ от SWIFT — остановка торгов на MOEX",
        "severity": 0.95,
        "market_impact_pct": -15.0,
        "source": "historical",
    },
    {
        "date": date(2022, 3, 8),
        "event_type": "corporate",
        "title": "Массовый уход западных компаний из РФ",
        "severity": 0.85,
        "market_impact_pct": -10.0,
        "source": "historical",
    },
    {
        "date": date(2022, 3, 15),
        "event_type": "sanctions",
        "title": "Санкции ЕС против российского угля и СПГ",
        "severity": 0.7,
        "market_impact_pct": -5.0,
        "source": "historical",
    },
    {
        "date": date(2022, 3, 24),
        "event_type": "oil_shock",
        "title": "Нефть Brent выше $130",
        "severity": 0.6,
        "market_impact_pct": 3.0,
        "source": "historical",
    },
    {
        "date": date(2022, 4, 8),
        "event_type": "sanctions",
        "title": "Пятый пакет санкций ЕС — уголь, технологии",
        "severity": 0.7,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2022, 4, 29),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 14%",
        "severity": 0.5,
        "market_impact_pct": 3.0,
        "source": "historical",
    },
    {
        "date": date(2022, 5, 8),
        "event_type": "sanctions",
        "title": "Шестой пакет санкций ЕС — нефтяное эмбарго",
        "severity": 0.75,
        "market_impact_pct": -5.0,
        "source": "historical",
    },
    {
        "date": date(2022, 5, 26),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 11%",
        "severity": 0.55,
        "market_impact_pct": 4.0,
        "source": "historical",
    },
    {
        "date": date(2022, 6, 10),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 9.5%",
        "severity": 0.5,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2022, 7, 22),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 8%",
        "severity": 0.45,
        "market_impact_pct": 2.5,
        "source": "historical",
    },
    {
        "date": date(2022, 9, 21),
        "event_type": "geopolitical",
        "title": "Объявление частичной мобилизации",
        "severity": 0.9,
        "market_impact_pct": -8.0,
        "source": "historical",
    },
    {
        "date": date(2022, 9, 30),
        "event_type": "geopolitical",
        "title": "Присоединение ДНР/ЛНР/Херсона/Запорожья",
        "severity": 0.8,
        "market_impact_pct": -5.0,
        "source": "historical",
    },
    {
        "date": date(2022, 10, 10),
        "event_type": "terror",
        "title": "Взрыв на Крымском мосту",
        "severity": 0.7,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2022, 10, 28),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 7.5%",
        "severity": 0.25,
        "market_impact_pct": 0.5,
        "source": "historical",
    },
    {
        "date": date(2022, 11, 1),
        "event_type": "sanctions",
        "title": "Price cap на нефть РФ от G7",
        "severity": 0.65,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2022, 12, 5),
        "event_type": "sanctions",
        "title": "Вступление в силу эмбарго ЕС на нефть РФ",
        "severity": 0.7,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2022, 12, 16),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 7.5%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2023, 1, 5),
        "event_type": "oil_shock",
        "title": "Нефть Brent упала до $75",
        "severity": 0.35,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2023, 2, 5),
        "event_type": "oil_shock",
        "title": "Нефтяное эмбарго ЕС на нефтепродукты РФ",
        "severity": 0.55,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2023, 2, 10),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 7.5%",
        "severity": 0.2,
        "market_impact_pct": 0.5,
        "source": "historical",
    },
    {
        "date": date(2023, 3, 10),
        "event_type": "global_crisis",
        "title": "Банкротство Silicon Valley Bank — паника",
        "severity": 0.65,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2023, 3, 20),
        "event_type": "global_crisis",
        "title": "Поглощение Credit Suisse UBS — кризис банков",
        "severity": 0.6,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2023, 3, 24),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 7.5%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2023, 4, 28),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 7.5%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2023, 5, 26),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 7.5%",
        "severity": 0.2,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2023, 6, 9),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 7.5%",
        "severity": 0.2,
        "market_impact_pct": 0.5,
        "source": "historical",
    },
    {
        "date": date(2023, 6, 24),
        "event_type": "geopolitical",
        "title": "Мятеж Пригожина — марш на Москву",
        "severity": 0.9,
        "market_impact_pct": -6.0,
        "source": "historical",
    },
    {
        "date": date(2023, 7, 21),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 8.5% — инфляция растёт",
        "severity": 0.6,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2023, 8, 15),
        "event_type": "rate_decision",
        "title": "ЦБ экстренно поднял ставку до 12%",
        "severity": 0.75,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2023, 9, 15),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 13%",
        "severity": 0.6,
        "market_impact_pct": -1.5,
        "source": "historical",
    },
    {
        "date": date(2023, 10, 7),
        "event_type": "geopolitical",
        "title": "Нападение ХАМАС на Израиль — рост нефти",
        "severity": 0.6,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2023, 10, 27),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 15%",
        "severity": 0.65,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2023, 12, 15),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 16%",
        "severity": 0.65,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2024, 1, 15),
        "event_type": "rate_decision",
        "title": "Начало года — ставка ЦБ 16%, инфляция 7.4%",
        "severity": 0.35,
        "market_impact_pct": -1.0,
        "source": "historical",
    },
    {
        "date": date(2024, 2, 16),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 16%",
        "severity": 0.3,
        "market_impact_pct": 0.5,
        "source": "historical",
    },
    {
        "date": date(2024, 3, 1),
        "event_type": "sanctions",
        "title": "Новые санкции США к 2-летию СВО",
        "severity": 0.55,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2024, 3, 15),
        "event_type": "political",
        "title": "Президентские выборы в РФ — победа Путина",
        "severity": 0.3,
        "market_impact_pct": 1.0,
        "source": "historical",
    },
    {
        "date": date(2024, 3, 22),
        "event_type": "terror",
        "title": "Теракт в Крокус Сити Холле",
        "severity": 0.75,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2024, 4, 26),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 16%",
        "severity": 0.3,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2024, 5, 19),
        "event_type": "geopolitical",
        "title": "Начало ядерных учений РФ — рост геополитики",
        "severity": 0.5,
        "market_impact_pct": -2.5,
        "source": "historical",
    },
    {
        "date": date(2024, 6, 7),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 16% — жёсткий сигнал",
        "severity": 0.35,
        "market_impact_pct": -1.0,
        "source": "historical",
    },
    {
        "date": date(2024, 7, 26),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 18%",
        "severity": 0.7,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2024, 9, 13),
        "event_type": "rate_decision",
        "title": "ЦБ повысил ставку до 19%",
        "severity": 0.7,
        "market_impact_pct": -2.0,
        "source": "historical",
    },
    {
        "date": date(2024, 10, 11),
        "event_type": "sanctions",
        "title": "Ужесточение вторичных санкций США",
        "severity": 0.6,
        "market_impact_pct": -3.0,
        "source": "historical",
    },
    {
        "date": date(2024, 11, 6),
        "event_type": "political",
        "title": "Победа Трампа на выборах президента США",
        "severity": 0.55,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2024, 12, 20),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 21%",
        "severity": 0.4,
        "market_impact_pct": -0.5,
        "source": "historical",
    },
    {
        "date": date(2025, 1, 1),
        "event_type": "macro_data",
        "title": "Инфляция в РФ стабилизируется ниже 10%",
        "severity": 0.3,
        "market_impact_pct": 1.0,
        "source": "historical",
    },
    {
        "date": date(2025, 2, 14),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 21%",
        "severity": 0.3,
        "market_impact_pct": 0.0,
        "source": "historical",
    },
    {
        "date": date(2025, 3, 1),
        "event_type": "geopolitical",
        "title": "Мирные переговоры РФ-Украина — надежда на деэскалацию",
        "severity": 0.55,
        "market_impact_pct": 3.0,
        "source": "historical",
    },
    {
        "date": date(2025, 3, 21),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 20% — первый сигнал смягчения",
        "severity": 0.7,
        "market_impact_pct": 4.0,
        "source": "historical",
    },
    {
        "date": date(2025, 4, 25),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 19% — продолжение смягчения",
        "severity": 0.6,
        "market_impact_pct": 3.0,
        "source": "historical",
    },
    {
        "date": date(2025, 5, 1),
        "event_type": "macro_data",
        "title": "ВВП РФ +3.5% в Q1 2025",
        "severity": 0.3,
        "market_impact_pct": 1.5,
        "source": "historical",
    },
    {
        "date": date(2025, 6, 13),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 18%",
        "severity": 0.55,
        "market_impact_pct": 2.5,
        "source": "historical",
    },
    {
        "date": date(2025, 7, 1),
        "event_type": "macro_data",
        "title": "Снижение инфляции в РФ до 6.5%",
        "severity": 0.3,
        "market_impact_pct": 1.0,
        "source": "historical",
    },
    {
        "date": date(2025, 7, 25),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 17%",
        "severity": 0.5,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2025, 8, 5),
        "event_type": "global_crisis",
        "title": "Торговая война США-КНР — пошлины 50%",
        "severity": 0.6,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2025, 9, 12),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 16%",
        "severity": 0.5,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2025, 11, 1),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 15%",
        "severity": 0.45,
        "market_impact_pct": 1.5,
        "source": "historical",
    },
    {
        "date": date(2025, 12, 19),
        "event_type": "rate_decision",
        "title": "ЦБ сохранил ставку 15%",
        "severity": 0.25,
        "market_impact_pct": 0.5,
        "source": "historical",
    },
    {
        "date": date(2026, 1, 15),
        "event_type": "oil_shock",
        "title": "Нефть Brent упала до $55 из-за перенасыщения",
        "severity": 0.65,
        "market_impact_pct": -4.0,
        "source": "historical",
    },
    {
        "date": date(2026, 2, 5),
        "event_type": "sanctions",
        "title": "Смягчение санкций в рамках мирного соглашения",
        "severity": 0.65,
        "market_impact_pct": 5.0,
        "source": "historical",
    },
    {
        "date": date(2026, 2, 14),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 14%",
        "severity": 0.5,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2026, 3, 15),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 13%",
        "severity": 0.45,
        "market_impact_pct": 1.5,
        "source": "historical",
    },
    {
        "date": date(2026, 4, 5),
        "event_type": "oil_shock",
        "title": "Нефть Brent восстановилась до $65",
        "severity": 0.3,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2026, 4, 24),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 12.5%",
        "severity": 0.45,
        "market_impact_pct": 2.0,
        "source": "historical",
    },
    {
        "date": date(2026, 5, 10),
        "event_type": "macro_data",
        "title": "ВВП РФ +4% — рекордный рост за 5 лет",
        "severity": 0.35,
        "market_impact_pct": 2.5,
        "source": "historical",
    },
    {
        "date": date(2026, 6, 5),
        "event_type": "rate_decision",
        "title": "ЦБ снизил ставку до 12% — темпы замедляются",
        "severity": 0.4,
        "market_impact_pct": 1.0,
        "source": "historical",
    },
    {
        "date": date(2026, 6, 23),
        "event_type": "rate_decision",
        "title": "ЦБ опустил ставку на 0.25% — до 11.75%",
        "severity": 0.45,
        "market_impact_pct": 3.0,
        "source": "historical",
    },
]
